import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Link from 'next/link'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <p>hello</p>
      <Link href="/posts/first-post"><a>点击去到first-post页面</a></Link>
    </div>
  )
}
